id = "pinescript"
name = "PineScript"
version = "0.0.0"
schema_version = 1
summary = "Pine Script language support for Zed"
description = "Syntax highlighting and snippets for TradingView's Pine Script (v5/v6)"
authors = ["daniel-lucas-silva"]
repository = "https://github.com/daniel-lucas-silva/zed-extensions"
license = "MIT"

[grammars.pinescript]
repository = "https://github.com/daniel-lucas-silva/zed-extensions"
rev = "28c8836008952c2296bddc1a7c326747b21357a8"
path = "extensions/pinescript/tree-sitter"
