name = "Pine Script"
grammar = "pinescript"
path_suffixes = ["pine", "pinescript"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
]
autoclose_before = "}])>""`
